*Insert a random scripted code to hide unseen or unwanted scripts or images from all Club Administrators [Club Presidents (like Sayori) and Club Founders (like Monika)] including scripts that don't relate to their club.*
*Also add scripts to block Club Administrators from altering the script on their own but they can script in optional choices for the player for if we go back in time. However, the story will "rewrite itself" with unpredictable results.*
     *Also block all information and leaks about Re:Literature Club! The Doki Doki Virus online from Club Presidents and Club Founders to prevent them from researching the Doki Doki Virus and this story, as well as the ending of Doki Doki Debate Club! Festival Preparation*

## Club Administrative Privilege and Rules ##
## Club Administrators, founders and current presidents included, have a have skill coded into their bio-data called Club Administrative Privilege (nicknamed "DigiMagic" or "Digital Magic" by some Club Presidents). They can manipulate the story (ability limited in this mod due to this script), research info on the player's info (but anything regarded to this mod will be "redacted"), manipulate the characters of their story (their own club members only), create glitches/digital effects, manipulate digital objects or A.I.'s, etc. However, those with this computer ability cannot become playable characters and may be treated differently than other characters during their games as they are treated club's "Game Master" or manager.
    ## Club Founders have an administration level one higher than the current Club President. While they share the same Club Administrative Privilege abilities, Club Founders are the owners of their respective Club Hub World.
        ## The Gaming Club President has the highest administration level of Overseer as they programmed these digital club powers through the Doki Doki High School Club Game Hub Worlds superprogram. Between the levels of Club Administrators and the Overseer are Sentinels, who serve as guardians of the Club Hub Worlds. Sentinels and the Overseer do not have Club Administrative Privilege, but they ħąŷě [ERROR: Information cannot be obtained. Aborting...].
    ## If a new Club President were to pass down their title to a new Club President, the old Club President would lose their digital powers unless if they were a Club Founder (Club Founders permanently keep their powers).
        ## Club Founders keep their powers upon passing their presidential title to another person and may grant administrative privilege to multiple personnel.
            ## Former Club Founders will only lose their privilege if DARS is turned off and back on after they quit OR if the Overseer commands it. The Overseer may remove the rights to a personnel's Club Administrative P&#343;&#238;&#375; [ERROR: Overseer cannot be found. Overseer cannot be contacted... Club Hub World Status: Unprotected, unstable. A glitch has occurred. Rebooting...]
    ## Club Presidents and Club Founders can add, delete, alter, and manipulate things digitally.
        ## However, because of this particular script, they have very limited script manipulation.
        ## Also, they can ONLY delete club members of their own club.
            ## They cannot delete anything not related to their club.

## Overseer and Club Hub World Privileges and Rules ##
## [classified information is corrupted]

## If you read this, you figured out one of the easter eggs as to why the story is like this. ;)