*Insert a random scripted code to hide unseen or unwanted scripts or images from Club Presidents (like Sayori) and Club Founders (like Monika) including scripts that don't relate to their club.*
*Also add scripts to block Club Presidents and Club Founders from altering the script on their own but they can script in optional choices for the player for if we go back in time. However, the story will "rewrite itself" with unpredictable results.*
    *Also block all information and leaks about Re:Literature Club! The Doki Doki Virus online from Club Presidents and Club Founders to prevent them from researching the Doki Doki Virus and this story, as well as the ending of Doki Doki Debate Club! Festival Preparation*

## Club Presidential Abilities and Rules ##
## Club Founders and Club Presidents nearly have the same powers. They can manipulate the story (ability limited in this mod due to this script), research info on the player's info (but anything regarded to this mod will be "redacted"), manipulate the characters of their story (their own club members only), create glitches/digital effects, manipulate digital objects or A.I.'s, etc.
   ## Club Founders have an administration level one higher than the current Club President.
       ## The Gaming Club President has the highest administration level as they programmed these digital club powers through their Doki Doki High School Club Game Hub Worlds program.
   ## If a new Club President were to pass down their title to a new Club President, the old Club President would lose their digital powers unless if they were a Club Founder (Club Founders permanently keep their powers).
       ## Club Founders keep their powers upon passing their presidential title to another person.
           ## Former Club Founders will only lose their powers if DARS is turned off and back on after they quit.
   ## Club Presidents and Club Founders can add, delete, alter, and manipulate things digitally.
       ## However, because of this particular script, they have very limited script manipulation.
       ## Also, they can ONLY delete club members of their own club.
           ## They cannot delete anything not related to their club.

## If you read this, you figured out one of the easter eggs as to why the story is like this. ;)